title: Fian Eko Saputra # your name (or website title) here
logo: "/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! You can view my Data Science projects here.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/fian-eko-saputra-4a2014128/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-4JQPNDNLHS # your Google Analytics tracking ID here
